version: '3.4'

services:
  gdaxstreamreader:
    image: ${DOCKER_REGISTRY-}gdaxstreamreader
    build:
      context: .
      dockerfile: RedisLoader/Dockerfile
    links:
    - nginx
  nginx:
    image: paulgwebster/nginx-gdax-ws-wss-stepup:latest